language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/travis/.sonar/cache
  - $HOME/travis/.sonarscanner/
  - $HOME/.sonarscanner/sonar-scanner-2.8
sudo: false
install: true
jdk:
  - oraclejdk8
script:  mvn -q -Pproduction-mode test
notifications:
    slack: tpfinal:HiKM45Mt99yllzQnQRGdIpNQ
